{% set version = "2.11.4" %}

package:
  name: pygmo
  version: {{ version }}

source:
  url: https://github.com/esa/pagmo2/archive/v{{ version }}.tar.gz
  sha256: 7756cf4b4a427a856137c40c3fdf27422fcf546249b70f9ba4c213ef1fbee051

build:
  number: 3
  skip: true  # [(win and py<35) or win32]
  ignore_run_exports:
    # pagmo-devel will automatically
    # put nlopt and ipopt as run dependencies,
    # but we don't actually need any symbol
    # from these libraries in pygmo's module.
    # Thus, remove them from the runtime
    # requirements.
    - nlopt
    - ipopt  # [win]

requirements:
  build:
    - cmake
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - pagmo-devel
    - boost
    - boost-cpp
    - numpy
    - cloudpickle
    - ipyparallel  # [py<38]
    - python
  run:
    - boost
    - boost-cpp
    - {{ pin_compatible('numpy') }}
    - cloudpickle
    - ipyparallel  # [py<38]
    - python

about:
  home: https://esa.github.io/pagmo2/
  license: GPL v3 and LGPL v3
  license_file: COPYING.lgpl3
  summary: 'A C++ / Python platform to perform parallel computations of optimisation tasks (global and local) via the asynchronous generalized island model'

extra:
  recipe-maintainers:
    - ccordoba12
    - bluescarni
    - darioizzo
