{% set version = "2.15.0" %}

package:
  name: pygmo
  version: {{ version }}

source:
  url: https://github.com/esa/pygmo2/archive/v{{ version }}.tar.gz
  sha256: 0f45636d47d5309f5f3d771e6677437f9d8de96cbad8b4f2758fa79c856022cc

build:
  number: 0
  skip: true  # [py<35]
  ignore_run_exports:
    # pagmo-devel will automatically
    # put nlopt and ipopt as run dependencies,
    # but we don't actually need any symbol
    # from these libraries in pygmo's module.
    # Thus, remove them from the runtime
    # requirements.
    - nlopt
    - ipopt  # [unix]

requirements:
  build:
    - cmake
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('c') }}              # [not win]
    - vs2017_{{ target_platform  }}    # [win]
  host:
    - pagmo-devel
    - boost-cpp
    - numpy
    - cloudpickle
    - ipyparallel  # [py<38]
    - python
    - networkx
  run:
    - {{ pin_compatible('boost-cpp', max_pin='x.x') }}
    - {{ pin_compatible('numpy') }}
    - cloudpickle
    - ipyparallel  # [py<38]
    - python
    - networkx

about:
  home: https://esa.github.io/pygmo2/
  license: MPL-2.0
  license_file: LICENSE
  summary: A Python platform to perform parallel computations of optimisation tasks (global and local) via the asynchronous generalized island model

extra:
  recipe-maintainers:
    - ccordoba12
    - bluescarni
    - darioizzo
