{% set version = "2.4" %}

package:
  name: pygmo
  version: {{ version }}

source:
  url: https://github.com/esa/pagmo2/archive/v{{ version }}.tar.gz
  sha256: ebea1ba004b85f6199a9d53a5969e18449f2923c2976c465e5755d0a42efab7f

build:
  number: 0
  skip: true  # [(win and py27) or win32]

requirements:
  build:
    - toolchain
    - cmake
    - pagmo     {{ version }}
    - eigen
    - nlopt
    - boost     1.63.*
    - numpy     x.x
    - cloudpickle
    - ipyparallel
    - python
    - ipopt             # [unix]
  run:
    - pagmo     {{ version }}
    - nlopt
    - boost     1.63.*
    - numpy     x.x
    - cloudpickle
    - ipyparallel
    - python
    - ipopt             # [unix]

about:
  home: https://esa.github.io/pagmo2/
  license: GPL v3 and LGPL v3
  license_file: COPYING.lgpl3
  summary: 'A C++ / Python platform to perform parallel computations of optimisation tasks (global and local) via the asynchronous generalized island model'

extra:
  recipe-maintainers:
    - xantares
    - ccordoba12
    - bluescarni
    - darioizzo
