{% set version = "2.8" %}

package:
  name: pygmo
  version: {{ version }}

source:
  url: https://github.com/esa/pagmo2/archive/v{{ version }}.tar.gz
  sha256: 7eec84a0d6a1e4b99def01241f52678e749c16b0055d386d1a71d3ea8b8d2589

build:
  number: 0
  skip: true  # [(win and py<36) or win32]

requirements:
  build:
    - cmake
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - pagmo     {{ version }}
    - eigen
    - nlopt
    - boost
    - numpy
    - cloudpickle
    - ipyparallel
    - python
    - ipopt             # [unix]
  run:
    - pagmo     {{ version }}
    - nlopt
    - boost
    - {{ pin_compatible('numpy') }}
    - cloudpickle
    - ipyparallel
    - python
    - ipopt             # [unix]

about:
  home: https://esa.github.io/pagmo2/
  license: GPL v3 and LGPL v3
  license_file: COPYING.lgpl3
  summary: 'A C++ / Python platform to perform parallel computations of optimisation tasks (global and local) via the asynchronous generalized island model'

extra:
  recipe-maintainers:
    - ccordoba12
    - bluescarni
    - darioizzo
