{% set version = "2.19.5" %}

package:
  name: pygmo
  version: {{ version }}

source:
  url: https://github.com/esa/pygmo2/archive/v{{ version }}.tar.gz
  sha256: 742ff0c3d535cb2af94d5095968d8f29c23ed7bdbd4ddd8259ca787eef881aa2
  patches:
    - find_python_fix.diff

build:
  number: 1
  ignore_run_exports:
    # pagmo-devel will automatically
    # put nlopt and ipopt as run dependencies,
    # but we don't actually need any symbol
    # from these libraries in pygmo's module.
    # Thus, remove them from the runtime
    # requirements.
    - nlopt
    - ipopt

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - pybind11 >=2.10                        # [build_platform != target_platform]
    - cmake >=3.18
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - make    # [unix]
  host:
    - python
    - pybind11 >=2.10
    - pybind11-abi
    - pagmo-devel =2.19.*
    - boost-cpp
    - cloudpickle
    - ipyparallel
    - networkx
    - scipy
  run:
    - {{ pin_compatible('boost-cpp', max_pin='x.x') }}
    - numpy
    - cloudpickle
    - ipyparallel
    - python
    - networkx
    - scipy

about:
  home: https://esa.github.io/pygmo2/
  license: MPL-2.0
  license_file: LICENSE
  summary: A Python platform to perform parallel computations of optimisation tasks (global and local) via the asynchronous generalized island model

extra:
  recipe-maintainers:
    - ccordoba12
    - bluescarni
    - darioizzo
