{% set version = "2.16.0" %}

package:
  name: pygmo
  version: {{ version }}

source:
  url: https://github.com/esa/pygmo2/archive/v{{ version }}.tar.gz
  sha256: 9b202fa329186f9ba8297f640f885f009876ee0884789fa972636c401b5ce8b8

build:
  number: 1
  skip: true  # [py<35]
  ignore_run_exports:
    # pagmo-devel will automatically
    # put nlopt and ipopt as run dependencies,
    # but we don't actually need any symbol
    # from these libraries in pygmo's module.
    # Thus, remove them from the runtime
    # requirements.
    - nlopt
    - ipopt  # [unix]

requirements:
  build:
    - cmake
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
  host:
    - pagmo-devel
    - boost-cpp
    - numpy
    - cloudpickle
    - ipyparallel  # [py<38]
    - python
    - networkx
    - scipy
  run:
    - {{ pin_compatible('boost-cpp', max_pin='x.x') }}
    - {{ pin_compatible('numpy') }}
    - cloudpickle
    - ipyparallel  # [py<38]
    - python
    - networkx
    - scipy

about:
  home: https://esa.github.io/pygmo2/
  license: MPL-2.0
  license_file: LICENSE
  summary: A Python platform to perform parallel computations of optimisation tasks (global and local) via the asynchronous generalized island model

extra:
  recipe-maintainers:
    - ccordoba12
    - bluescarni
    - darioizzo
