{% set version = "2.10" %}

package:
  name: pygmo
  version: {{ version }}

source:
  url: https://github.com/esa/pagmo2/archive/v{{ version }}.tar.gz
  sha256: 2fa95e2b464ddeadb9fc09bd314081293f02a1b6abc11c0b05064729a077227c

build:
  number: 1001
  skip: true  # [(win and py<35) or win32]

requirements:
  build:
    - cmake
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - pagmo     {{ version }}
    - eigen
    - boost
    - numpy
    - cloudpickle
    - ipyparallel
    - python
  run:
    - pagmo     {{ version }}
    - boost
    - {{ pin_compatible('numpy') }}
    - cloudpickle
    - ipyparallel
    - python

about:
  home: https://esa.github.io/pagmo2/
  license: GPL v3 and LGPL v3
  license_file: COPYING.lgpl3
  summary: 'A C++ / Python platform to perform parallel computations of optimisation tasks (global and local) via the asynchronous generalized island model'

extra:
  recipe-maintainers:
    - ccordoba12
    - bluescarni
    - darioizzo
