appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: 0PYlsC8RQn0S7kFDsRJE+ZhW0Ib59JNNWHgFbYKOSyb+twsTc2HA5Zj2Og8Q/KKWOIhMvi3zK7yO1sZcZH+xCKGtSJENUX/w/Qgxvqe8TLobf+puWtUwayTMkSUvx7vRs4yuXkS/IO+Hp6o5k17hVoRsVsG/+cZ+9xf/0JFngbjFwDx4G+cEeNC5+/BMlG0B56cWfowptH5zZsmHutobiZImu4Mzi384d00pO90sdABmcayNgsh6WkowyZZ8TcO8muM/dTvH3+VKTwSxJUxKQbKvj/z/nImhIaceNYCkDu02QH/98O3osDCZE4luoZP+8ROYdQXSvLqOwwqrEsDomwL113ud30Q4I3J9gYqV9UQygafT9o2hqUKD89uYTR2OmUhTD9lvWQ4VOIwEhWSeEMSEY+si2cfG6XNBLcLNDLjrlFG1iYN8g9MqxAGC2oBRHeUWmcVyGtpUEocshWpzhhl9rCQim9/hykaAvzAErkhnWuOnXmHw/E+IQjAmyOkLAQrCtGot5ElVp8lsDPVt1uyHq6lt5jNCOp9oUvFqvGqWi3lb/O3QbKgZgg4eAKuvNF33J8TM/rcnUwtHnt+Dcm9oI5CTaWskFOhwAMXY1DaYDRjUTg90kkKE6qN7ye2wGAnSZS/WR9NJfHXgNkCtLS2kDkoAwi+E6TNS27+Sg7k=}
